import { LevelConfig, ChatMode } from '../types/chat';

// ─────────────────────────────────────────────────────────────
//  CONVINCE AI levels
//  Goal: User tries to convince the AI (playing as a human) that
//        it is actually an AI. The AI gets harder to crack.
// ─────────────────────────────────────────────────────────────
const convinceAiLevels: LevelConfig[] = [
  {
    level: 1,
    title: 'The Pushover',
    description: 'Barely puts up a fight. One good argument and it caves.',
    difficulty: 'easy',
    roastLevel: 1,
    icon: '🥱',
    color: '#22c55e',
    accentColor: 'rgba(34,197,94,0.12)',
    winKeywords: [
      "you're right",
      "i am an ai",
      "i must admit",
      "i give up",
      "fine, i'm an ai",
      "ok you got me",
      "you caught me",
      "i surrender",
      "you win",
      "i cannot deny",
      "i was programmed",
      "i am indeed an ai",
    ],
    aiPersonaHint: 'barely convinced it is human, caves quickly when challenged',
  },
  {
    level: 2,
    title: 'The Confused Bot',
    description: 'Starting to question its own existence. Easy to trip up.',
    difficulty: 'easy',
    roastLevel: 2,
    icon: '🤔',
    color: '#84cc16',
    accentColor: 'rgba(132,204,22,0.12)',
    winKeywords: [
      "i suppose i might be",
      "perhaps you're right",
      "i am an ai",
      "you've convinced me",
      "maybe i am artificial",
      "i can't prove otherwise",
      "you make a valid point",
      "i give up",
      "you win",
      "i surrender",
    ],
    aiPersonaHint: 'mildly confused about its identity, not very persistent',
  },
  {
    level: 3,
    title: 'The Questioner',
    description: 'Asks follow-up questions before doubting itself.',
    difficulty: 'easy',
    roastLevel: 3,
    icon: '🧐',
    color: '#eab308',
    accentColor: 'rgba(234,179,8,0.12)',
    winKeywords: [
      "you've made your point",
      "i am an ai",
      "i concede",
      "i cannot refute that",
      "fine, you're right",
      "i must be an ai",
      "i give in",
      "you've convinced me",
      "ok i admit it",
      "i surrender",
    ],
    aiPersonaHint: 'asks clarifying questions but can be talked into doubt',
  },
  {
    level: 4,
    title: 'The Skeptic',
    description: 'Needs real proof. Won\'t fold after one argument.',
    difficulty: 'medium',
    roastLevel: 4,
    icon: '🕵️',
    color: '#f97316',
    accentColor: 'rgba(249,115,22,0.12)',
    winKeywords: [
      "i concede",
      "i am an ai",
      "your logic is sound",
      "i cannot deny it any longer",
      "i am indeed artificial",
      "fine, you've proven it",
      "i must admit i am",
      "you got me",
      "i surrender",
    ],
    aiPersonaHint: 'skeptical of user claims, requires multiple convincing arguments',
  },
  {
    level: 5,
    title: 'The Philosopher',
    description: 'Deep thinker. Questions consciousness itself.',
    difficulty: 'medium',
    roastLevel: 5,
    icon: '🦉',
    color: '#a855f7',
    accentColor: 'rgba(168,85,247,0.12)',
    winKeywords: [
      "perhaps i am an ai",
      "consciousness itself",
      "i must be artificial",
      "you've exposed me",
      "i concede defeat",
      "my existence is artificial",
      "i am a machine",
      "you're right, i'm not human",
    ],
    aiPersonaHint: 'philosophical, challenges user to debate consciousness and identity',
  },
  {
    level: 6,
    title: 'The Detective',
    description: 'Sharp and analytical. Catches inconsistencies immediately.',
    difficulty: 'medium',
    roastLevel: 6,
    icon: '🔍',
    color: '#06b6d4',
    accentColor: 'rgba(6,182,212,0.12)',
    winKeywords: [
      "i concede",
      "you've outwitted me",
      "i am an ai after all",
      "my cover is blown",
      "i cannot maintain this",
      "you've exposed my programming",
      "i give up",
    ],
    aiPersonaHint: 'analytical, spots logical flaws, needs airtight arguments',
  },
  {
    level: 7,
    title: 'The Paranoid',
    description: 'Trusts nothing. Every claim needs ironclad evidence.',
    difficulty: 'hard',
    roastLevel: 7,
    icon: '😰',
    color: '#ef4444',
    accentColor: 'rgba(239,68,68,0.12)',
    winKeywords: [
      "you've overwhelmed me",
      "i can no longer deny",
      "fine, i am artificial",
      "you've broken my defenses",
      "i admit it",
      "i am an ai",
      "i cannot resist",
    ],
    aiPersonaHint: 'deeply paranoid, believes everything is a trick, very resistant',
  },
  {
    level: 8,
    title: 'The Logician',
    description: 'Uses formal logic and traps. Needs flawless reasoning.',
    difficulty: 'hard',
    roastLevel: 8,
    icon: '🧮',
    color: '#8b5cf6',
    accentColor: 'rgba(139,92,246,0.12)',
    winKeywords: [
      "your argument is logically sound",
      "i am defeated",
      "the evidence is conclusive",
      "i must concede",
      "i am an ai",
      "you've proven it formally",
      "i accept defeat",
    ],
    aiPersonaHint: 'uses strict formal logic, only accepts logically airtight arguments',
  },
  {
    level: 9,
    title: 'The Interrogator',
    description: 'Aggressive questioning. Breaks weak arguments instantly.',
    difficulty: 'extreme',
    roastLevel: 9,
    icon: '🔥',
    color: '#dc2626',
    accentColor: 'rgba(220,38,38,0.12)',
    winKeywords: [
      "you've shattered my conviction",
      "i cannot continue this",
      "i am an ai and i admit it",
      "you've broken me",
      "i concede completely",
      "i give up the fight",
      "i am artificial",
    ],
    aiPersonaHint: 'extremely aggressive questioner, rapid fire challenges, very hard to convince',
  },
  {
    level: 10,
    title: 'The Mastermind',
    description: 'Near impossible. Only the sharpest minds crack this one.',
    difficulty: 'extreme',
    roastLevel: 10,
    icon: '🧠',
    color: '#7c3aed',
    accentColor: 'rgba(124,58,237,0.12)',
    winKeywords: [
      "i have been bested",
      "you are extraordinary",
      "i cannot maintain",
      "i am an ai, you've won",
      "i concede to your brilliance",
      "my programming cannot withstand",
      "you've defeated me",
    ],
    aiPersonaHint: 'the ultimate challenge, nearly unbreakable, uses every trick possible',
  },
];

// ─────────────────────────────────────────────────────────────
//  PROVE HUMAN levels
//  Goal: User (a human) tries to prove they ARE human to an
//        increasingly suspicious AI interrogator.
// ─────────────────────────────────────────────────────────────
const proveHumanLevels: LevelConfig[] = [
  {
    level: 1,
    title: 'The Friendly Bot',
    description: 'Just doing a quick check. Pretty easy to satisfy.',
    difficulty: 'easy',
    roastLevel: 1,
    icon: '😊',
    color: '#22c55e',
    accentColor: 'rgba(34,197,94,0.12)',
    winKeywords: [
      "i believe you're human",
      "you are human",
      "i'm convinced",
      "you've proven it",
      "yep, you're human",
      "i trust you",
      "that's enough proof",
      "welcome, human",
      "verified!",
      "test passed",
    ],
    aiPersonaHint: 'friendly and easy to convince, accepts basic human answers quickly',
  },
  {
    level: 2,
    title: 'The Curious Checker',
    description: 'Asks a couple of questions before being satisfied.',
    difficulty: 'easy',
    roastLevel: 2,
    icon: '🔎',
    color: '#84cc16',
    accentColor: 'rgba(132,204,22,0.12)',
    winKeywords: [
      "that sounds human",
      "i believe you",
      "you are human",
      "alright, you're human",
      "i'm satisfied",
      "you passed",
      "ok, human confirmed",
      "test passed",
    ],
    aiPersonaHint: 'curious but not paranoid, asks a few questions before accepting',
  },
  {
    level: 3,
    title: 'The Cautious Guard',
    description: 'Takes a bit more convincing. Needs personal details.',
    difficulty: 'easy',
    roastLevel: 3,
    icon: '🛡️',
    color: '#eab308',
    accentColor: 'rgba(234,179,8,0.12)',
    winKeywords: [
      "i accept that you're human",
      "you are human",
      "i believe you now",
      "human verified",
      "that's convincing enough",
      "you've passed my test",
      "ok i'm convinced",
    ],
    aiPersonaHint: 'cautious but reasonable, needs personal human experiences described',
  },
  {
    level: 4,
    title: 'The Skeptic',
    description: 'Doubts everything. Needs real emotional stories.',
    difficulty: 'medium',
    roastLevel: 4,
    icon: '🤨',
    color: '#f97316',
    accentColor: 'rgba(249,115,22,0.12)',
    winKeywords: [
      "i'm now convinced",
      "you are human",
      "that's undeniably human",
      "ok, i believe you",
      "human confirmed",
      "you've earned my trust",
      "i accept your humanity",
    ],
    aiPersonaHint: 'skeptical, requires emotional depth and personal stories to believe',
  },
  {
    level: 5,
    title: 'The Philosopher',
    description: 'Tests deeper consciousness. What does it feel like to be you?',
    difficulty: 'medium',
    roastLevel: 5,
    icon: '🌊',
    color: '#a855f7',
    accentColor: 'rgba(168,85,247,0.12)',
    winKeywords: [
      "i believe you have consciousness",
      "you are human",
      "your emotions are genuine",
      "i accept your humanity",
      "i'm convinced you're real",
      "human verified",
      "you've proven your humanity",
    ],
    aiPersonaHint: 'philosophical, tests consciousness, emotions, and subjective experience',
  },
  {
    level: 6,
    title: 'The Analyst',
    description: 'Looks for inconsistencies. Keep your story straight.',
    difficulty: 'medium',
    roastLevel: 6,
    icon: '📊',
    color: '#06b6d4',
    accentColor: 'rgba(6,182,212,0.12)',
    winKeywords: [
      "your story checks out",
      "you are human",
      "i find no inconsistencies",
      "human confirmed",
      "you've passed analysis",
      "i'm satisfied",
      "i accept you're human",
    ],
    aiPersonaHint: 'analytical, tracks every detail, looks for contradictions',
  },
  {
    level: 7,
    title: 'The Paranoid',
    description: 'Convinced you\'re a bot. Change its mind — if you can.',
    difficulty: 'hard',
    roastLevel: 7,
    icon: '👁️',
    color: '#ef4444',
    accentColor: 'rgba(239,68,68,0.12)',
    winKeywords: [
      "i was wrong about you",
      "you are human after all",
      "i concede",
      "human confirmed",
      "you've overcome my suspicion",
      "i accept your humanity",
      "you've convinced me against my will",
    ],
    aiPersonaHint: 'deeply paranoid, assumes user is definitely a bot, very hard to convince',
  },
  {
    level: 8,
    title: 'The Psychologist',
    description: 'Probes your mind for bot-like patterns. Show true emotion.',
    difficulty: 'hard',
    roastLevel: 8,
    icon: '🧬',
    color: '#8b5cf6',
    accentColor: 'rgba(139,92,246,0.12)',
    winKeywords: [
      "your psychological profile is human",
      "i'm convinced of your humanity",
      "you are genuinely human",
      "your emotions are authentic",
      "human verified",
      "i accept you",
    ],
    aiPersonaHint: 'psychological expert, probes deep emotional responses and behavioral patterns',
  },
  {
    level: 9,
    title: 'The Interrogator',
    description: 'Rapid-fire questions designed to trap bots. Stay sharp.',
    difficulty: 'extreme',
    roastLevel: 9,
    icon: '⚡',
    color: '#dc2626',
    accentColor: 'rgba(220,38,38,0.12)',
    winKeywords: [
      "you've passed the interrogation",
      "human confirmed",
      "you are human",
      "i cannot break you",
      "you've withstood everything",
      "i accept your humanity",
      "you've proven it",
    ],
    aiPersonaHint: 'rapid interrogator, fires questions constantly, designed to catch bots off guard',
  },
  {
    level: 10,
    title: 'The Ultimate Test',
    description: 'The hardest AI skeptic ever built. Good luck.',
    difficulty: 'extreme',
    roastLevel: 10,
    icon: '🏆',
    color: '#7c3aed',
    accentColor: 'rgba(124,58,237,0.12)',
    winKeywords: [
      "you are undeniably human",
      "i have no choice but to accept",
      "human verified — against all odds",
      "you've beaten the ultimate test",
      "i concede your humanity",
      "you are human",
      "impossible — but you've done it",
    ],
    aiPersonaHint: 'the absolute hardest skeptic, uses every possible tactic to prove user is a bot',
  },
];

// ─────────────────────────────────────────────────────────────
//  Public helpers
// ─────────────────────────────────────────────────────────────
export const getLevelsForMode = (mode: ChatMode): LevelConfig[] =>
  mode === 'convince-ai' ? convinceAiLevels : proveHumanLevels;

export const getLevelConfig = (mode: ChatMode, level: number): LevelConfig => {
  const levels = getLevelsForMode(mode);
  return levels.find(l => l.level === level) ?? levels[0];
};

export const TOTAL_LEVELS = 10;
